### ISSUE TITLE
Add sample how to user WatermelonDB

### ISSUE THREAD

**Issue by enieber** [enieber/rn-db-example#4]
add sample how to use in react-native this database,  [WatermelonDB](https://github.com/Nozbe/WatermelonDB) 

- [x] get item
- [x] create item
- [x] update item
- [x] delete item

**Comment by KrisLau** [comment]
Commenting to follow this as I would love to see more WatermelonDB examples/tutorials!

**Comment by enieber** [comment]
thanks @ValcineiJr to make this sample:

https://github.com/ValcineiJr/WatermelonDB-YT
